# Generated by Django 3.0.4 on 2020-04-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecode',
            options={'verbose_name': 'Fichier de code', 'verbose_name_plural': 'Fichiers de code'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='tuto_python',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tuto python'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='tuto_r',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tuto R'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_submitted',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload_file.FileCsv', verbose_name='Fichier de prédiction (csv)'),
        ),
    ]
